import prisma from '../prisma'
import { clInstaller } from './CLInstaller'
import { githubCLI } from './GitHubCLI'
import { vercelCLI } from './VercelCLI'
import { opencodeCLI } from './OpencodeCLI'
import { codeReviewer } from './CodeReviewer'
import { taskPlanner } from './TaskPlanner'
import { randomUUID } from 'crypto'

const MAX_RETRIES = 3

export async function executeTask(taskId: string): Promise<void> {
  console.log(`[Executor] Starting task ${taskId}`)
  
  const task = await prisma.autonomousTask.findUnique({ where: { id: taskId } })
  if (!task) {
    console.error(`[Executor] Task ${taskId} not found`)
    return
  }

  try {
    // Step 1: Install CLIs
    await prisma.autonomousRun.create({
      data: { taskId, step: 'install', status: 'running', logs: 'Installing CLIs...' }
    })
    
    await clInstaller.ensureInstalled()
    
    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'install' },
      data: { status: 'success', output: 'All CLIs installed', duration: 0 }
    })

    // Step 2: Planning (AI analysis)
    await prisma.autonomousRun.create({
      data: { taskId, step: 'planning', status: 'running', logs: 'Analyzing task...' }
    })
    
    const planning = await taskPlanner.analyze(task.description, task.type as any)
    
    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { 
        status: 'executing',
        type: planning.type,
        priority: planning.priority,
        description: planning.description,
        subtasks: planning.subtasks,
        planningResult: JSON.stringify(planning)
      }
    })
    
    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'planning' },
      data: { status: 'success', output: JSON.stringify(planning), duration: 0 }
    })

    // Step 3: Execute subtasks with Opencode
    const branchName = `autonomous/${taskId.slice(0, 8)}-${planning.description.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}`
    
    await prisma.autonomousRun.create({
      data: { taskId, step: 'coding', status: 'running', logs: 'Generating code...' }
    })

    // Create branch
    await githubCLI.createBranch(branchName)

    let subtasks = planning.subtasks
    let allSuccess = true

    for (let i = 0; i < subtasks.length; i++) {
      const subtask = subtasks[i]
      console.log(`[Executor] Executing subtask ${i + 1}/${subtasks.length}: ${subtask.description}`)
      
      const result = await opencodeCLI.execute(subtask.description)
      
      subtasks[i] = {
        ...subtask,
        status: result.success ? 'completed' : 'failed',
        output: result.output
      }

      if (!result.success) {
        allSuccess = false
        break
      }
    }

    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { subtasks }
    })

    if (!allSuccess) {
      throw new Error('One or more subtasks failed')
    }

    // Step 4: Commit
    await prisma.autonomousRun.create({
      data: { taskId, step: 'commit', status: 'running', logs: 'Committing changes...' }
    })

    const commitMsg = `[AIHub] ${planning.description}\n\n🤖 Generated by Autonomous AIHub`
    const commitHash = await githubCLI.commitFiles(commitMsg)
    
    await githubCLI.pushBranch(branchName)

    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { branch: branchName, commitHash }
    })

    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'commit' },
      data: { status: 'success', output: commitHash, duration: 0 }
    })

    // Step 5: Create PR
    await prisma.autonomousRun.create({
      data: { taskId, step: 'pr', status: 'running', logs: 'Creating PR...' }
    })

    const prBody = `## Summary
${planning.description}

## Subtasks
${subtasks.map(s => `- [${s.status === 'completed' ? 'x' : ' '}] ${s.description}`).join('\n')}

## Technical Details
- Branch: ${branchName}
- Commit: ${commitHash}

🤖 Generated by Autonomous AIHub`

    const pr = await githubCLI.createPR(`[AIHub] ${planning.description}`, prBody, branchName)
    await githubCLI.addPRLabels(pr.number, ['autonomous', 'aihub-generated'])

    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { status: 'reviewing', prUrl: pr.url, prNumber: pr.number }
    })

    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'pr' },
      data: { status: 'success', output: pr.url, duration: 0 }
    })

    // Step 6: Code Review
    await prisma.autonomousRun.create({
      data: { taskId, step: 'review', status: 'running', logs: 'Running code review...' }
    })

    const reviewResults = await codeReviewer.runChecks()
    
    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { reviewResults }
    })

    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'review' },
      data: { status: 'success', output: JSON.stringify(reviewResults), duration: 0 }
    })

    // Auto-approve if pass
    if (codeReviewer.canAutoMerge(reviewResults)) {
      await codeReviewer.approvePR(pr.number)
    } else {
      await codeReviewer.addPRComment(pr.number, `## AIHub Review Issues\n\nLint: ${reviewResults.lint}\nTypecheck: ${reviewResults.typecheck}\nSecurity: ${reviewResults.security}\n\n⚠️ Please review manually.`)
    }

    // Step 7: Deploy Preview
    await prisma.autonomousRun.create({
      data: { taskId, step: 'deploy', status: 'running', logs: 'Deploying preview...' }
    })

    const deployResult = await vercelCLI.deployPreview(branchName)
    
    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { status: 'deploying', testResults: { deploy: deployResult } }
    })

    await prisma.autonomousRun.updateMany({
      where: { taskId, step: 'deploy' },
      data: { status: deployResult.success ? 'success' : 'failed', output: deployResult.url || deployResult.error, duration: 0 }
    })

    if (!deployResult.success) {
      throw new Error(`Deploy failed: ${deployResult.error}`)
    }

    // Step 8: Auto Merge (if all checks pass)
    if (codeReviewer.canAutoMerge(reviewResults)) {
      await prisma.autonomousRun.create({
        data: { taskId, step: 'merge', status: 'running', logs: 'Merging PR...' }
      })

      try {
        await githubCLI.mergePR(pr.number)
        
        // Delete branch after merge
        await githubCLI.deleteBranch(branchName)
        
        await prisma.autonomousTask.update({
          where: { id: taskId },
          data: { status: 'merged', completedAt: new Date() }
        })

        await prisma.autonomousRun.updateMany({
          where: { taskId, step: 'merge' },
          data: { status: 'success', output: 'Merged to main', duration: 0 }
        })

        console.log(`[Executor] Task ${taskId} completed successfully!`)
      } catch (error: any) {
        console.log('[Executor] Auto-merge failed (may need manual review):', error.message)
        
        await prisma.autonomousRun.updateMany({
          where: { taskId, step: 'merge' },
          data: { status: 'failed', error: error.message, duration: 0 }
        })
      }
    } else {
      console.log(`[Executor] Task ${taskId} ready for manual review`)
    }

  } catch (error: any) {
    console.error(`[Executor] Task ${taskId} failed:`, error)
    
    await prisma.autonomousTask.update({
      where: { id: taskId },
      data: { status: 'failed', errorLog: error.message }
    })

    await prisma.autonomousRun.create({
      data: { taskId, step: 'error', status: 'failed', error: error.message, logs: 'Task failed' }
    })
  }
}